### ISSUE TITLE
bottom and top edge apples

### ISSUE THREAD

**Issue by IPNugget** [Lord-of-the-Galaxy/Snake-AI#2]
the AI will go for any apple on the screen except for apples on the top or bottom edge

**Comment by Lord-of-the-Galaxy** [comment]
Hmm I hadn't noticed this before, I shall look into it

**Comment by Lord-of-the-Galaxy** [comment]
The current AI just strongly learns to avoid the edges, and it's hard to get it to pick up anything on the edges.
To fix this I would have to revamp the AI, so unfortunately I cannot fix this issue.
